/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

/**
 *
 * @author Isaac
 */
public class menuAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuAdmin
     */
    public menuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmpleadoIrA = new javax.swing.JButton();
        btnProductoIrA = new javax.swing.JButton();
        btnRegresarIr = new javax.swing.JButton();

        btnEmpleadoIrA.setText("Empleado");
        btnEmpleadoIrA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoIrAActionPerformed(evt);
            }
        });

        btnProductoIrA.setText("Producto");
        btnProductoIrA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoIrAActionPerformed(evt);
            }
        });

        btnRegresarIr.setText("Regresar");
        btnRegresarIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarIrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresarIr)
                    .addComponent(btnProductoIrA)
                    .addComponent(btnEmpleadoIrA))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnEmpleadoIrA)
                .addGap(18, 18, 18)
                .addComponent(btnProductoIrA)
                .addGap(18, 18, 18)
                .addComponent(btnRegresarIr)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadoIrAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoIrAActionPerformed
        // TODO add your handling code here:
        registroEmpleado llamar=new registroEmpleado();
        menu.jDPEscritorio.add(llamar);
        llamar.toFront();
        llamar.setVisible(true);
    }//GEN-LAST:event_btnEmpleadoIrAActionPerformed

    private void btnProductoIrAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoIrAActionPerformed
        // TODO add your handling code here:
        Producto llamar=new Producto();
        menu.jDPEscritorio.add(llamar);
        llamar.toFront();
        llamar.setVisible(true);
    }//GEN-LAST:event_btnProductoIrAActionPerformed

    private void btnRegresarIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarIrActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRegresarIrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpleadoIrA;
    private javax.swing.JButton btnProductoIrA;
    private javax.swing.JButton btnRegresarIr;
    // End of variables declaration//GEN-END:variables
}
